// balance

export const FETCH_BALANCE_REQUEST = 'FETCH_BALANCE_REQUEST'
export const FETCH_BALANCE_FAILURE = 'FETCH_BALANCE_FAILURE'
export const FETCH_BALANCE_SUCCESS = 'FETCH_BALANCE_SUCCESS'

// invoices

export const FETCH_INVOICES_REQUEST = 'FETCH_INVOICES_REQUEST'
export const FETCH_INVOICES_FAILURE = 'FETCH_INVOICES_FAILURE'
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS'

// payments

export const FETCH_PAYMENTS_REQUEST = 'FETCH_PAYMENTS_REQUEST'
export const FETCH_PAYMENTS_FAILURE = 'FETCH_PAYMENTS_FAILURE'
export const FETCH_PAYMENTS_SUCCESS = 'FETCH_PAYMENTS_SUCCESS'

// withdrawals

export const FETCH_WITHDRAWALS_REQUEST = 'FETCH_WITHDRAWALS_REQUEST'
export const FETCH_WITHDRAWALS_FAILURE = 'FETCH_WITHDRAWALS_FAILURE'
export const FETCH_WITHDRAWALS_SUCCESS = 'FETCH_WITHDRAWALS_SUCCESS'
